### ISSUE TITLE
ON/OFF with manually added devices

### ISSUE THREAD

**Issue by Nadias-jp** [Haoyu-UT/HomeAssistantNatureRemo#5]
Thanks for the great integration.

This is not a problem report but a request.
We have multiple blinds in our house and have been using Nature Remo to open/close them.

On the Nature Remo app:
"Blind1" -> OPEN STOP CLOSE

Nature Remo app consists of three buttons like "OPEN, STOP and CLOSE".
I wanted to use this to do OPEN/CLOSE with automation, but only one action could be selected with the button.

Now on the Nature Remo App
"Blind1 OPEN" -> OPEN
"Blind1 CLOSE" -> CLOSE

Not knowing how else to do it, I assigned one button to one device and used it.

It would be very useful if you could create an entity for the number of buttons.

Please let me know if my understanding is wrong.

**Comment by Haoyu-UT** [comment]
Hi! Thank you for your feedback.
If I understand correctly, you want to select a signal to send inside the automation process. Your device should also have registered a select entity, so you can select a signal before pressing the button. (The button entity sends whatever is selected by the select entity, so always select one before pressing the button.) The attached image shows the way of achieving this inside automation for now.
<img width="787" alt="Image" src="https://github.com/user-attachments/assets/8a51e286-3430-43f5-8b69-fc7be8a1bb24" />

Besides I think it is a good point that we can create a separate button for each signal. This will make automation much easier.

**Comment by Haoyu-UT** [comment]
To select & send from the UI, my recommendation is to add a horizontal stack component to the dashboard. This is an example for controlling my audio device.

<img width="372" alt="Image" src="https://github.com/user-attachments/assets/6da8f2de-19a3-43de-bd78-3c0a73ca8061" />

This YAML snippet creates the UI component I have shown above.
```
type: horizontal-stack
cards:
  - features:
      - type: select-options
    type: tile
    entity: select.signals_audio
    vertical: false
    tap_action:
      action: call-service
      service: button.press
      target:
        entity_id: button.send_signal_audio
    icon_tap_action:
      action: call-service
      service: button.press
      target:
        entity_id: button.send_signal_audio
    icon: mdi:cast-audio
```
Or you can create the same component from UI like this.

<img width="376" alt="Image" src="https://github.com/user-attachments/assets/35aa11d6-cdef-491d-b776-6405690e6c5f" />
